services:
  caddy:
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PORT=80
  backend-0:
    restart: no
    command: ["hypercorn", "app.main:app", "--reload", "--bind", "::"]
    develop:
      watch:
        - path: .
          action: sync
          target: /app
          ignore:
            - .venv
        - path: ./pyproject.toml
          action: rebuild
    environment:
      - MACHINE_ID=0
  backend-1:
    restart: no
    command: ["hypercorn", "app.main:app", "--reload", "--bind", "::"]
    develop:
      watch:
        - path: .
          action: sync
          target: /app
          ignore:
            - .venv
        - path: ./pyproject.toml
          action: rebuild
    environment:
      - MACHINE_ID=1
  backend-2:
    restart: no
    command: ["hypercorn", "app.main:app", "--reload", "--bind", "::"]
    develop:
      watch:
        - path: .
          action: sync
          target: /app
          ignore:
            - .venv
        - path: ./pyproject.toml
          action: rebuild
    environment:
      - MACHINE_ID=2
  frontend:
    restart: no
    ports:
      - "5173:80"
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:80
