services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - backend-0
      - backend-1
      - backend-2
  backend-0:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    build:
      context: .
    restart: always
    env_file:
      - .env
  backend-1:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    build:
      context: .
    restart: always
    env_file:
      - .env
  backend-2:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    build:
      context: .
    restart: always
    env_file:
      - .env
